services:
    redis:
        networks:
            uninuvola:
                ipv4_address: ${REDIS_IP}
        container_name: redis
        image: redis
        command: redis-server --loglevel warning

networks:
  uninuvola:
    external: true
