services:
    redis:
        networks:
            uninuvola:
                ipv4_address: 10.9.245.4
        container_name: redis
        image: redis
        command: redis-server --save 60 1 --loglevel warning
        volumes:
          - redis:/data

volumes:
    redis: {}

networks:
  uninuvola:
    external: true
